### ISSUE TITLE
Completion does not work with eselect-repository

### ISSUE THREAD

**Issue by mgorny** [gentoo/gentoo-zsh-completions#12]
Relaying https://github.com/mgorny/eselect-repository/issues/2 since I don't use zsh. Please let me know if that's a problem you're going to fix within this package, or if I need to do anything to help.

Quoting the bug by @Q3CPMA:
> first, thanks a lot for this simple and lightweight layman replacement (especially when seeing all the stuff that layman pulls). When trying to complete eselect repository under zsh, I get 
> `_values:compvalues:10: invalid value definition: disable [-f] (<name>|<index>)... Disable specified repositories without removing their contents.`
> I don't know if I should take it to https://github.com/gentoo/gentoo-zsh-completions, but since it's the only eselect module failing, I'll try here first.
>
> Using eselect-repository-2 and app-shells/gentoo-zsh-completions-20150103

**Comment by radhermit** [comment]
Looks like it's trying to parse the usage info for eselect repository and failing. We could preempt that by adding explicit support for the repository subcmd.

**Comment by PetrusZ** [comment]
```
➜ sudo eselect repository
_values:compvalues:11: invalid value definition: disable [-f] (<name>|<index>)... Disable specified repositories without removing their contents
_values:compvalues:11: invalid value definition: disable [-f] (<name>|<index>)... Disable specified repositories without removing their contents
_values:compvalues:11: invalid value definition: disable [-f] (<name>|<index>)... Disable specified repositories without removing their contents
```
bug still the same ...

**Comment by xdch47** [comment]
did you update to `app-shells/gentoo-zsh-completions-99999999` ?

**Comment by PetrusZ** [comment]
99999999 works fine, thx. So ... why don't we bump a new version?

**Comment by xdch47** [comment]
nobody tagged gentoo-zsh-completions in order to bump it.

@radhermit  dropped the maintainer-ship.
@msva is the only person merging something from time to time.
in other words completions/pull/18/commits/45247d12f9acb312c6de4d01db7dcd46d6397a28 took nearly one year, my gpg key expired in the meantime.... this project is abandoned.

**Comment by PetrusZ** [comment]
emm ... ok, thank for you explanation ....

**Comment by radhermit** [comment]
I would note that anyone is welcome to proxy-maintain the related ebuild for this and Gentoo infra could probably figure out how to give you commit access to the repo as well, so if you want to make it more active feel free to step up.

**Comment by msva** [comment]
В письме от пятница, 7 февраля 2020 г. 01:12:56 +07 пользователь xdch47 
написал:
> nobody tagged gentoo-zsh-completions in order to bump it.
> 
> @radhermit  dropped the maintainer-ship.
> @msva is the only person merging something from time to time.
> in other words
> completions/pull/18/commits/45247d12f9acb312c6de4d01db7dcd46d6397a28 took
> nearly one year, my gpg key expired in the meantime.... this project is
> abandoned.

Well, actually, we're all just in heavy lack of time.
I've plans for bumping, but ATM I'm too busy at work.

I'll try to bump in the near time.
