### ISSUE TITLE
completion does not work with =cat/package- type atoms

### ISSUE THREAD

**Issue by covici** [gentoo/gentoo-zsh-completions#7]
Hi.  In the released version of your package, I cannot use completion with atoms of the form =<category>/<packagename>-<version> after the  =<category> completion does not work.

**Comment by radhermit** [comment]
Works for me. Are you escaping the equals sign on the command line? You'll need to do that so it doesn't get interpreted.

**Comment by radhermit** [comment]
Closing this as works for me. If something is still broken please provide better, full atom examples that aren't completing properly for you.
